blank_issues_enabled: false
contact_links:
  - name: Fragen & Diskussionen
    url: https://github.com/MachMitGoslar/GS_MMH_WEB/discussions
    about: Fuer allgemeine Fragen bitte eine Diskussion starten statt ein Issue.
